version: "3.9"

networks:
  web:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asterope-frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.asterope.rule=Host(`asterope.neovara.ltd`)"
      - "traefik.http.routers.asterope.entrypoints=websecure"
      - "traefik.http.routers.asterope.tls.certresolver=le"
      - "traefik.http.services.asterope.loadbalancer.server.port=4208"
    networks:
      - web
